const root_path = "https://raw.githubusercontent.com/klippero/code-snippet-in-web/refs/heads/main/";

const recorridos = {
    "POO":
    {
        label: "Programación Orientada a Objetos",
        temas: 
        [
            { 
                label: 'Entorno',
                secciones: [
                    { label: 'Intérprete' },
                    { label: 'IDE Visual Studio Code' },
                    { label: 'Debugger' }
                ]
            },
            { label: 'Clases y objetos' },
            { label: 'Métodos' },
            { label: 'Constructor' },
            { label: 'Atributos' },
            { label: 'String Formatting' },
            { label: 'Métodos que modifican el estado' },
            { label: 'Parámetros de un método' },
            { label: 'Parámetros de un constructor' },
            { label: 'Valores por defecto para parámetros' },
            { label: 'Lectura por teclado' },
            { label: 'return' },
            { label: 'Convertir a string' },
            { label: 'Consultar un atributo' },
            { label: 'IRB: interactive Ruby' },
            { label: 'Operadores aritméticos' },
            { label: 'Operadores relacionales' },
            { label: 'if else' },
            { label: 'Operadores lógicos' },
            { label: 'Métodos ? y return de expresiones lógicas' },
            { label: 'while' },
            { label: 'times / each' },
            { label: 'Listas' },
            { label: 'Implementando operadores' },
            { label: 'Asignación abreviada' },
            { label: 'Comentarios' },
            { label: 'Constantes' },
            { label: 'Diccionarios' },
            { label: 'Parámetros requeridos, por defecto y opcionales' },
            { label: 'Keyword arguments' },
            {
                label: 'Excepciones',
                secciones: [
                    { label: 'Qué son' },
                    { label: 'Cómo se pueden controlar' },
                    { label: 'Excepciones comunes' },
                    { label: 'Cómo se lanzan' },
                ]
            },
            {
                label: 'Visibilidad de atributos (accessors)',
                secciones: [
                    { label: 'Lectura (getter)' },
                    { label: 'Escritura (setter)' },
                ]
            },
            {
                label: 'Visibilidad de métodos',
                secciones: [
                    { label: 'Públicos' },
                    { label: 'Privados' },
                    { label: 'Protegidos' },
                    { label: 'Visibilidad al final de la clase' },
                ]
            },
            { 
                label: 'Herencia',
                secciones: [
                    { label: 'Qué es la herencia' },
                    { label: 'Sobreescritura ó overriding (cambiar el comportamiento)' },
                    { label: 'Sobreescritura ó overriding (extender el comportamiento con super)' },
                    { label: 'Especialización en la construcción (comportamiento)' },
                    { label: 'Especialización en la construcción (atributos)' },
                ]
            },
            { label: 'return implícito' }
        ]
    }
};

const lenguajes = {
    'rb': {
        label: 'Ruby',
        extension: 'rb'
    },
    'py': {
        label: 'Python',
        extension: 'py'
    }
};

const retos = {
    '1an': { label: "Mi gato Pipo", recorrido: "POO", tema: 1, coleccion: "animales", out_por_lenguaje: true},
    '10b': { label: "Pregunta el número de viajes", recorrido: "POO", tema: 10, coleccion: "bonobús"},
    '11b': { label: "Uso de return en info", recorrido: "POO", tema: 11, coleccion: "bonobús"},
    '12b': { label: "Convertir a texto", recorrido: "POO", tema: 12, coleccion: "bonobús"},
    '4b': { label: "Atributo viajes", recorrido: "POO", tema: 4, coleccion: "bonobús"},
    '8b': { label: "Número de viajes en el constructor", recorrido: "POO", tema: 8, coleccion: "bonobús"},
    '9b': { label: "Por defecto 10 viajes", recorrido: "POO", tema: 9, coleccion: "bonobús"},
    '4c': { label: "Atributo saldo", recorrido: "POO", tema: 4, coleccion: "cuenta"},
    '5c': { label: "Mostrar saldo bonito", recorrido: "POO", tema: 5, coleccion: "cuenta"},
    '6c1': { label: "Intereses", recorrido: "POO", tema: 6, coleccion: "cuenta"},
    '6c2': { label: "Retirar fondos", recorrido: "POO", tema: 6, coleccion: "cuenta"},
    '7c': { label: "Ingreso y reintegro", recorrido: "POO", tema: 7, coleccion: "cuenta"},
    '8c-cuenta': { label: "Cantidad inicial al crear la cuenta", recorrido: "POO", tema: 8, coleccion: "cuenta"},
    '8c': { label: "Apertura de cuenta con aportación", recorrido: "POO", tema: 8, coleccion: "cuenta"},
    '9c': { label: "Por defecto 0€", recorrido: "POO", tema: 9, coleccion: "cuenta"},
    '12d': { label: "Convertir a texto", recorrido: "POO", tema: 12, coleccion: "dado"},
    '13d': { label: "Tirada de 2 dados", recorrido: "POO", tema: 13, coleccion: "dado"},
    '6d': { label: "Tirar", recorrido: "POO", tema: 6, coleccion: "dado"},
    '13f': { label: "Dos máquinas de frío", recorrido: "POO", tema: 13, coleccion: "combi"},
    '6f': { label: "Abrir y cerrar puertas", recorrido: "POO", tema: 6, coleccion: "combi"},
    '7f': { label: "Cambiar temperatura", recorrido: "POO", tema: 7, coleccion: "combi"},
    '8f': { label: "Temperatura inicial", recorrido: "POO", tema: 8, coleccion: "combi"},
    '9f': { label: "Temperaturas para creación y fijar temperatura por defecto", recorrido: "POO", tema: 9, coleccion: "combi"},
    '11g': { label: "Pasar Celsius a Fahrenheit", recorrido: "POO", tema: 11, coleccion: "grados"},
    '11i': { label: "Calcula área y perímetro", recorrido: "POO", tema: 11, coleccion: "círculo"},
    '10io-t': { label: "Pregunta nombre y años", recorrido: "POO", tema: 10, coleccion: "entradasalida"},
    '13j': { label: "Juevo con posición y vidas", recorrido: "POO", tema: 13, coleccion: "juego"},
    '12m': { label: "Lotería Primitiva", recorrido: "POO", tema: 12, coleccion: "primitiva"},
    '13m': { label: "getter reintegro", recorrido: "POO", tema: 13, coleccion: "primitiva"},
    '12p': { label: "Convertir a texto", recorrido: "POO", tema: 12, coleccion: "punto"},
    '8p1': { label: "Construir punto con x,y", recorrido: "POO", tema: 8, coleccion: "punto"},
    '8p2': { label: "Mover a nueva posición", recorrido: "POO", tema: 8, coleccion: "punto"},
    '8p3': { label: "Mover a origen", recorrido: "POO", tema: 8, coleccion: "punto"},
    '8p4': { label: "Volver al punto anterior", recorrido: "POO", tema: 8, coleccion: "punto"},
    '9p1': { label: "Por defecto se crea 0,0", recorrido: "POO", tema: 9, coleccion: "punto"},
    '9p2': { label: "Por defecto se mueve a 0,0", recorrido: "POO", tema: 9, coleccion: "punto"},
    '11u': { label: "Área", recorrido: "POO", tema: 11, coleccion: "cuadrado"},
    '12u': { label: "Convertir a texto", recorrido: "POO", tema: 12, coleccion: "cuadrado"},
    '13u': { label: "getter lado", recorrido: "POO", tema: 13, coleccion: "cuadrado"},
    '20a1': { label: "20a1", recorrido: "POO", tema: 20, coleccion: "linea"},
    '20a2': { label: "20a2", recorrido: "POO", tema: 20, coleccion: "linea"},
    '21a': { label: "21a", recorrido: "POO", tema: 21, coleccion: "linea"},
    '23a-relacionales': { label: "23a-relacionales", recorrido: "POO", tema: 23, coleccion: "linea"},
    '23a': { label: "23a", recorrido: "POO", tema: 23, coleccion: "linea"},
    '24a': { label: "24a", recorrido: "POO", tema: 24, coleccion: "linea"},
    '29a1': { label: "Gráfico con key arguments", recorrido: "POO", tema: 29, coleccion: "linea"},
    '29a2': { label: "Gráfico con key arguments con valores por defecto", recorrido: "POO", tema: 29, coleccion: "linea"},
    '15b': { label: "Métodos para recarga y usar", recorrido: "POO", tema: 15, coleccion: "bonobús"},
    '17b': { label: "17b", recorrido: "POO", tema: 17, coleccion: "bonobús"},
    '18b': { label: "18b", recorrido: "POO", tema: 18, coleccion: "bonobús"},
    '19b': { label: "19b", recorrido: "POO", tema: 19, coleccion: "bonobús"},
    '15c-a': { label: "Pedir nombre y aportación", recorrido: "POO", tema: 15, coleccion: "cuenta"},
    '15c-b': { label: "Crear objeto y convertir a texto", recorrido: "POO", tema: 15, coleccion: "cuenta"},
    '15c-c': { label: "Ingresar", recorrido: "POO", tema: 15, coleccion: "cuenta"},
    '15c-d': { label: "Cálculo de intereses", recorrido: "POO", tema: 15, coleccion: "cuenta"},
    '15c-e': { label: "Liquidar intereses", recorrido: "POO", tema: 15, coleccion: "cuenta"},
    '15c-f': { label: "Retirar", recorrido: "POO", tema: 15, coleccion: "cuenta"},
    '17c': { label: "17c", recorrido: "POO", tema: 17, coleccion: "cuenta"},
    '18c': { label: "18c", recorrido: "POO", tema: 18, coleccion: "cuenta"},
    '26cr1': { label: "add", recorrido: "POO", tema: 26, coleccion: "registradora"},
    '26cr2': { label: "to_f", recorrido: "POO", tema: 26, coleccion: "registradora"},
    '26cr3': { label: "take", recorrido: "POO", tema: 26, coleccion: "registradora"},
    '26cr4': { label: "Operador <<", recorrido: "POO", tema: 26, coleccion: "registradora"},
    '27cr': { label: "", recorrido: "POO", tema: 27, coleccion: "registradora"},
    '17d1': { label: "17d1", recorrido: "POO", tema: 17, coleccion: "dado"},
    '17d2': { label: "17d2", recorrido: "POO", tema: 17, coleccion: "dado"},
    '18e1': { label: "18e1", recorrido: "POO", tema: 18, coleccion: "fechas"},
    '18e2': { label: "18e2", recorrido: "POO", tema: 18, coleccion: "fechas"},
    '18e3': { label: "18e3", recorrido: "POO", tema: 18, coleccion: "fechas"},
    '17edades': { label: "17edades", recorrido: "POO", tema: 17, coleccion: "edades"},
    '27ed1': { label: "27ed1", recorrido: "POO", tema: 27, coleccion: "edades"},
    '27ed2': { label: "27ed2", recorrido: "POO", tema: 27, coleccion: "edades"},
    '27ed3': { label: "27ed3", recorrido: "POO", tema: 27, coleccion: "edades"},
    '27ed4': { label: "27ed4", recorrido: "POO", tema: 27, coleccion: "edades"},
    '27ed5': { label: "27ed5", recorrido: "POO", tema: 27, coleccion: "edades"},
    '27ed6': { label: "27ed6", recorrido: "POO", tema: 27, coleccion: "edades"},
    '22est-media': { label: "22est-media", recorrido: "POO", tema: 22, coleccion: "estadistica"},
    '22est-mediana': { label: "22est-mediana", recorrido: "POO", tema: 22, coleccion: "estadistica"},
    '27est-moda1': { label: "27est-moda1", recorrido: "POO", tema: 27, coleccion: "estadistica"},
    '27est-moda2': { label: "27est-moda2", recorrido: "POO", tema: 27, coleccion: "estadistica"},
    '17f': { label: "17f", recorrido: "POO", tema: 17, coleccion: "combi"},
    '19f': { label: "19f", recorrido: "POO", tema: 19, coleccion: "combi"},
    '23fr': { label: "23fr", recorrido: "POO", tema: 23, coleccion: "fracción"},
    '15g': { label: "15g", recorrido: "POO", tema: 15, coleccion: "grados"},
    '0hw': { label: "Hello world", recorrido: "POO", tema: 0, coleccion: "hw"},
    '15l1': { label: "15l1", recorrido: "POO", tema: 15, coleccion: "elipse"},
    '15l2': { label: "15l2", recorrido: "POO", tema: 15, coleccion: "elipse"},
    '22le-contar': { label: "22le-contar", recorrido: "POO", tema: 22, coleccion: "listaenteros"},
    '22le-contarPares': { label: "22le-contarPares", recorrido: "POO", tema: 22, coleccion: "listaenteros"},
    '22le-esta': { label: "22le-esta", recorrido: "POO", tema: 22, coleccion: "listaenteros"},
    '22le-hayPar': { label: "22le-hayPar", recorrido: "POO", tema: 22, coleccion: "listaenteros"},
    '22le-mayor': { label: "22le-mayor", recorrido: "POO", tema: 22, coleccion: "listaenteros"},
    '22le-par': { label: "22le-par", recorrido: "POO", tema: 22, coleccion: "listaenteros"},
    '22le-pos-item': { label: "22le-pos-item", recorrido: "POO", tema: 22, coleccion: "listaenteros"},
    '22le-pos-mayor': { label: "22le-pos-mayor", recorrido: "POO", tema: 22, coleccion: "listaenteros"},
    '22le-remove': { label: "22le-remove", recorrido: "POO", tema: 22, coleccion: "listaenteros"},
    '22le-removeDuplicates': { label: "22le-removeDuplicates", recorrido: "POO", tema: 22, coleccion: "listaenteros"},
    '22le-restaListas': { label: "22le-restaListas", recorrido: "POO", tema: 22, coleccion: "listaenteros"},
    '22le-restaListasDestr': { label: "22le-restaListasDestr", recorrido: "POO", tema: 22, coleccion: "listaenteros"},
    '22le-shufle': { label: "22le-shufle", recorrido: "POO", tema: 22, coleccion: "listaenteros"},
    '22le-shufleDest': { label: "22le-shufleDest", recorrido: "POO", tema: 22, coleccion: "listaenteros"},
    '22le-smallest': { label: "22le-smallest", recorrido: "POO", tema: 22, coleccion: "listaenteros"},
    '22le-suma': { label: "22le-suma", recorrido: "POO", tema: 22, coleccion: "listaenteros"},
    '22le-sumaListas': { label: "22le-sumaListas", recorrido: "POO", tema: 22, coleccion: "listaenteros"},
    '22le-sumaListasDestruct': { label: "22le-sumaListasDestruct", recorrido: "POO", tema: 22, coleccion: "listaenteros"},
    '23le-restaListas': { label: "23le-restaListas", recorrido: "POO", tema: 23, coleccion: "listaenteros"},
    '23le-sumaListas': { label: "23le-sumaListas", recorrido: "POO", tema: 23, coleccion: "listaenteros"},
    '23le-sumaListas2': { label: "23le-sumaListas2", recorrido: "POO", tema: 23, coleccion: "listaenteros"},
    '22lp-firstandlast': { label: "22lp-firstandlast", recorrido: "POO", tema: 22, coleccion: "listapalabras"},
    '22mbp1': { label: "22mbp1", recorrido: "POO", tema: 22, coleccion: "primitiva"},
    '22mbp2': { label: "22mbp2", recorrido: "POO", tema: 22, coleccion: "primitiva"},
    '22mbp3': { label: "22mbp3", recorrido: "POO", tema: 22, coleccion: "primitiva"},
    '22mbp4': { label: "22mbp4", recorrido: "POO", tema: 22, coleccion: "primitiva"},
    '22mp1': { label: "22mp1", recorrido: "POO", tema: 22, coleccion: "primitiva"},
    '22mp2': { label: "22mp2", recorrido: "POO", tema: 22, coleccion: "primitiva"},
    '26mp': { label: "26mp", recorrido: "POO", tema: 26, coleccion: "primitiva"},
    '27md-claves': { label: "27md-claves", recorrido: "POO", tema: 27, coleccion: "midiccionario"},
    '27md-inverso': { label: "27md-inverso", recorrido: "POO", tema: 27, coleccion: "midiccionario"},
    '27md-randomkey': { label: "27md-randomkey", recorrido: "POO", tema: 27, coleccion: "midiccionario"},
    '27md-valores': { label: "27md-valores", recorrido: "POO", tema: 27, coleccion: "midiccionario"},
    '17n1': { label: "17n1", recorrido: "POO", tema: 17, coleccion: "números"},
    '17n2': { label: "17n2", recorrido: "POO", tema: 17, coleccion: "números"},
    '19n': { label: "19n", recorrido: "POO", tema: 19, coleccion: "números"},
    '20n-factorial': { label: "20n-factorial", recorrido: "POO", tema: 20, coleccion: "números"},
    '20np1': { label: "20np1", recorrido: "POO", tema: 20, coleccion: "números"},
    '20np2': { label: "20np2", recorrido: "POO", tema: 20, coleccion: "números"},
    '20np3': { label: "20np3", recorrido: "POO", tema: 20, coleccion: "números"},
    '20np4': { label: "20np4", recorrido: "POO", tema: 20, coleccion: "números"},
    '20np5': { label: "20np5", recorrido: "POO", tema: 20, coleccion: "números"},
    '20np6': { label: "20np6", recorrido: "POO", tema: 20, coleccion: "números"},
    '20np7': { label: "20np7", recorrido: "POO", tema: 20, coleccion: "números"},
    '20np7-2': { label: "20np7-2", recorrido: "POO", tema: 20, coleccion: "números"},
    '20np8': { label: "20np8", recorrido: "POO", tema: 20, coleccion: "números"},
    '21n-a1': { label: "21n-a1", recorrido: "POO", tema: 21, coleccion: "números"},
    '21n-a2': { label: "21n-a2", recorrido: "POO", tema: 21, coleccion: "números"},
    '21n-a3': { label: "21n-a3", recorrido: "POO", tema: 21, coleccion: "números"},
    '21n-factorial': { label: "21n-factorial", recorrido: "POO", tema: 21, coleccion: "números"},
    '21np1': { label: "21np1", recorrido: "POO", tema: 21, coleccion: "números"},
    '21np2': { label: "21np2", recorrido: "POO", tema: 21, coleccion: "números"},
    '21np3': { label: "21np3", recorrido: "POO", tema: 21, coleccion: "números"},
    '21np4': { label: "21np4", recorrido: "POO", tema: 21, coleccion: "números"},
    '21np5': { label: "21np5", recorrido: "POO", tema: 21, coleccion: "números"},
    '21np6': { label: "21np6", recorrido: "POO", tema: 21, coleccion: "números"},
    '22n-divisores': { label: "22n-divisores", recorrido: "POO", tema: 22, coleccion: "números"},
    '15o1': { label: "15o1", recorrido: "POO", tema: 15, coleccion: "triángulo"},
    '15o2': { label: "15o2", recorrido: "POO", tema: 15, coleccion: "triángulo"},
    '21o': { label: "21o", recorrido: "POO", tema: 21, coleccion: "triángulo"},
    '15p1': { label: "15p1", recorrido: "POO", tema: 15, coleccion: "punto"},
    '15p2': { label: "15p2", recorrido: "POO", tema: 15, coleccion: "punto"},
    '15p3': { label: "15p3", recorrido: "POO", tema: 15, coleccion: "punto"},
    '18p': { label: "18p", recorrido: "POO", tema: 18, coleccion: "punto"},
    '19p1': { label: "19p1", recorrido: "POO", tema: 19, coleccion: "punto"},
    '19p2': { label: "19p2", recorrido: "POO", tema: 19, coleccion: "punto"},
    '19p3': { label: "19p3", recorrido: "POO", tema: 19, coleccion: "punto"},
    '23p': { label: "23p", recorrido: "POO", tema: 23, coleccion: "punto"},
    '9p3': { label: "Por defecto lo deja donde está", recorrido: "POO", tema: 9, coleccion: "punto"},
    '20n-primo1': { label: "20n-primo1", recorrido: "POO", tema: 20, coleccion: "primos"},
    '20n-primo2': { label: "20n-primo2", recorrido: "POO", tema: 20, coleccion: "primos"},
    '20n-primo3': { label: "20n-primo3", recorrido: "POO", tema: 20, coleccion: "primos"},
    '20n-primo4': { label: "20n-primo4", recorrido: "POO", tema: 20, coleccion: "primos"},
    '20n.siguientePrimo': { label: "20n.siguientePrimo", recorrido: "POO", tema: 20, coleccion: "primos"},
    '20.4.1.factores': { label: "20.4.1.factores", recorrido: "POO", tema: 20, coleccion: "primos"},
    '20.4.2.factores': { label: "20.4.2.factores", recorrido: "POO", tema: 20, coleccion: "primos"},
    '27.4.3.factores': { label: "27.4.3.factores", recorrido: "POO", tema: 27, coleccion: "primos"},
    '27.5.desfactoriza': { label: "27.5.desfactoriza", recorrido: "POO", tema: 27, coleccion: "primos"},
    '27.6.factores-negativos': { label: "27.6.factores-negativos", recorrido: "POO", tema: 27, coleccion: "primos"},
    '27.7.mcm': { label: "27.7.mcm", recorrido: "POO", tema: 27, coleccion: "primos"},
    '27.s.1.MCD': { label: "27.s.1.MCD", recorrido: "POO", tema: 27, coleccion: "primos"},
    '27.s.2.a.fraccion': { label: "27.s.2.a.fraccion", recorrido: "POO", tema: 27, coleccion: "primos"},
    '27.s.2.b.canonica': { label: "27.s.2.b.canonica", recorrido: "POO", tema: 27, coleccion: "primos"},
    '27.s.2.c.propia': { label: "27.s.2.c.propia", recorrido: "POO", tema: 27, coleccion: "primos"},
    '27.s.2.d.getPropia': { label: "27.s.2.d.getPropia", recorrido: "POO", tema: 27, coleccion: "primos"},
    '27.s.2.e.unidades': { label: "27.s.2.e.unidades", recorrido: "POO", tema: 27, coleccion: "primos"},
    '27.s.2.f.sumar': { label: "27.s.2.f.sumar", recorrido: "POO", tema: 27, coleccion: "primos"},
    '27.s.2.f2.sumar': { label: "27.s.2.f2.sumar", recorrido: "POO", tema: 27, coleccion: "primos"},
    '27.s.2.g.restar': { label: "27.s.2.g.restar", recorrido: "POO", tema: 27, coleccion: "primos"},
    '27.s.2.h.multiplicar': { label: "27.s.2.h.multiplicar", recorrido: "POO", tema: 27, coleccion: "primos"},
    '27.s.2.i.dividir': { label: "27.s.2.i.dividir", recorrido: "POO", tema: 27, coleccion: "primos"},
    '27.s.3.a.mixtos': { label: "27.s.3.a.mixtos", recorrido: "POO", tema: 27, coleccion: "primos"},
    '27.s.3.b.simplificar': { label: "27.s.3.b.simplificar", recorrido: "POO", tema: 27, coleccion: "primos"},
    '27.s.3.c.canonica': { label: "27.s.3.c.canonica", recorrido: "POO", tema: 27, coleccion: "primos"},
    '27.s.3.d.to_fraccion': { label: "27.s.3.d.to_fraccion", recorrido: "POO", tema: 27, coleccion: "primos"},
    '27.s.3.e.to_mixto': { label: "27.s.3.e.to_mixto", recorrido: "POO", tema: 27, coleccion: "primos"},
    '27.s.3.f.sumar': { label: "27.s.3.f.sumar", recorrido: "POO", tema: 27, coleccion: "primos"},
    '27.s.3.g.restar': { label: "27.s.3.g.restar", recorrido: "POO", tema: 27, coleccion: "primos"},
    '15r': { label: "15r", recorrido: "POO", tema: 15, coleccion: "rectángulo"},
    '21r': { label: "21r", recorrido: "POO", tema: 21, coleccion: "rectángulo"},
    '23r': { label: "23r", recorrido: "POO", tema: 23, coleccion: "rectángulo"},
    '24r': { label: "24r", recorrido: "POO", tema: 24, coleccion: "rectángulo"},
    '15t-dedos': { label: "15t-dedos", recorrido: "POO", tema: 15, coleccion: "aleatorio"},
    '20t1': { label: "20t1", recorrido: "POO", tema: 20, coleccion: "aleatorio"},
    '20t2': { label: "20t2", recorrido: "POO", tema: 20, coleccion: "aleatorio"},
    '20t3': { label: "20t3", recorrido: "POO", tema: 20, coleccion: "aleatorio"},
    '22t': { label: "22t", recorrido: "POO", tema: 22, coleccion: "aleatorio"},
    '23t': { label: "23t", recorrido: "POO", tema: 23, coleccion: "aleatorio"},
    '24tm1': { label: "24tm1", recorrido: "POO", tema: 24, coleccion: "tiempo"},
    '24tm2': { label: "24tm2", recorrido: "POO", tema: 24, coleccion: "tiempo"},
    '24tm3': { label: "24tm3", recorrido: "POO", tema: 24, coleccion: "tiempo"},
    '24tm4': { label: "24tm4", recorrido: "POO", tema: 24, coleccion: "tiempo"},
    '24tm5': { label: "24tm5", recorrido: "POO", tema: 24, coleccion: "tiempo"},
    '24tm6': { label: "24tm6", recorrido: "POO", tema: 24, coleccion: "tiempo"},
    '15u': { label: "15u", recorrido: "POO", tema: 15, coleccion: "cuadrado"},
    '20u': { label: "20u", recorrido: "POO", tema: 20, coleccion: "cuadrado"},
    '21u': { label: "21u", recorrido: "POO", tema: 21, coleccion: "cuadrado"},
    '23u0': { label: "23u0", recorrido: "POO", tema: 23, coleccion: "cuadrado"},
    '23u1': { label: "23u1", recorrido: "POO", tema: 23, coleccion: "cuadrado"},
    '23u2': { label: "23u2", recorrido: "POO", tema: 23, coleccion: "cuadrado"},
    '23u3': { label: "23u3", recorrido: "POO", tema: 23, coleccion: "cuadrado"},
    '28cr1': { label: "Parámetros por defecto", recorrido: "POO", tema: 28, coleccion: "registradora"},
    '28cr2': { label: "Parámetro esponja add", recorrido: "POO", tema: 28, coleccion: "registradora"},
    '28cr3': { label: "Parámetro esponja take", recorrido: "POO", tema: 28, coleccion: "registradora"},
    '28le-suma': { label: "Suma lista", recorrido: "POO", tema: 28, coleccion: "listaenteros"},
    '28c': { label: "Ingreso y reintegro con esponja", recorrido: "POO", tema: 28, coleccion: "cuenta"},
    '28a1': { label: "Gráfico con esponja", recorrido: "POO", tema: 28, coleccion: "linea"},
    '28a2': { label: "Gráfico con números", recorrido: "POO", tema: 28, coleccion: "linea"},
    '28a3': { label: "Gráfico con chars diferentes", recorrido: "POO", tema: 28, coleccion: "linea"},
    '28est': { label: "Con esponja", recorrido: "POO", tema: 28, coleccion: "estadistica"},
};

    const colecciones = {
    'animales': { label: 'animales' },
    'bonobús': { label: 'bonobús' },
    'cuenta': { label: 'cuenta' },
    'dado': { label: 'dado' },
    'combi': { label: 'frigorífico combi' },
    'estadistica': { label: 'estadística' },
    'grados': { label: 'grados' },
    'círculo': { label: 'círculo' },
    'entradasalida': { label: 'entradasalida' },
    'juego': { label: 'juego' },
    'primitiva': { label: 'primitiva' },
    'punto': { label: 'punto' },
    'cuadrado': { label: 'cuadrado' },
    'registradora':{label:'caja registradora'},
    'listaenteros':{label:'lista enteros'},
    'edades':{label:'Edades'},
    'midiccionario':{label:'midiccionario'},
    'linea':{label:'línea'}
    };

function insert(id,content)
{
    element = document.getElementById(id);
    element.textContent = content;
}

function insertA(id,content,link)
{
    element = document.getElementById(id);

    a = document.createElement("a");
    a.href = link;
    a.textContent = content;

    element.appendChild(a);
}
